Delete attachments of Cards in Folders and Lists
CMSC-129C-Projects/CalPal pull request #69
Opened 2021-06-09 08:59 UTC by drparcon

This pull requests solves the issue of attachments of cards in folders and lists not being deleted when the respective folder or list is deleted. This is handled by having a respective endpoint for folder and list and fetching that endpoint when a list or a folder is deleted. The database function for deleting a folder parses the folder's cards and calls the function to delete the attachments of that card. The database function for deleting a list parses the elements of a list and calls the function to delete attachments of a card if it finds a card and calls the function for delete folder attachments if it finds a folder.

2021-06-09 10:03 UTC, grantyap requested changes

2021-06-09 10:03 UTC, grantyap commented on src/components/List.svelte
>      $session.lists = $session.lists.filter((l) => {
Please add a new line here to visually separate the `fetch` from the rest of the code.

```suggestion
    });
    
    $session.lists = $session.lists.filter((l) => {
```

2021-06-09 10:03 UTC, grantyap commented on src/routes/api/_database.js
> +export async function deleteAttachmentsinFolder(userId, folderId) {
Please capitalize each succeeding word in function names.

```suggestion
export async function deleteAttachmentsInFolder(userId, folderId) {
```

2021-06-09 10:03 UTC, grantyap commented on src/routes/api/_database.js
> +export async function deleteAttachmentsinList(userId, listId) {
```suggestion
export async function deleteAttachmentsInList(userId, listId) {
```

2021-06-09 10:05 UTC, BigBlackLab19 approved these changes

2021-06-09 10:47 UTC, grantyap requested changes
Looks good so far!

Last thing is to get rid of the lint errors in AddCalendar.

2021-06-09 10:47 UTC, grantyap commented on src/routes/api/_database.js
> +  return;
Please remove this `return` statement also.

2021-06-10 08:06 UTC, drparcon commented
> 
> 
> One more minor change and this will be good to go. Last thing is to get rid of the lint errors in AddCalendar.

The same lint errors also exist in the development branch. I think it would be better to take care of them there before merging this branch into development.

2021-06-10 08:42 UTC, merged